rg                     = "rg-dev"
location               = "centralus"
service_principle_name = "aks_user001"
SUB_ID                 = "Enter Subscription ID"
cluster_name           = "AKS"
node_pool_name         = "aksnod"
keyvault_name          = "keyvault-dev"
