rg                     = "rg-stage"
location               = "centralus"
service_principle_name = "aks_stage"
SUB_ID                 = "Enter subscription id"
cluster_name           = "AKS"
node_pool_name         = "aksnod"
keyvault_name          = "keyvault-stage"
